import argparse
from pathlib import Path
from discovery import discover_services
from fault_parser import parse_fault_context
from logs_parser import parse_logs
from metrics_parser import parse_metrics_from_run_dir
from system_parser import parse_system
from traces_parser import parse_traces
from topology_parser import parse_static_topology, build_graph
from workload_parser import parse_workload_from_traces
from rca_features import build_rca_features, infer_service_health
from sla import evaluate_sla
from utils import ensure_dir, write_json, write_jsonl, read_json
from datetime import datetime


def derive_latency(metrics, traces):
    for edge, feats in traces.items():
        if "->" not in edge:
            continue

        _, dst = edge.split("->", 1)
        metrics.setdefault(dst, {})

        latency_ms = feats.get("latency_p95_us", 0.0) / 1000.0

        metrics[dst]["latency"] = max(
            metrics[dst].get("latency", 0.0),
            latency_ms
        )

        metrics[dst]["latency_ms"] = max(
            metrics[dst].get("latency_ms", 0.0),
            latency_ms
        )

    return metrics


def build_state(run_dir):
    run_dir = Path(run_dir)
    services = discover_services(run_dir)
    fault = parse_fault_context(run_dir)
    if fault.get("faulty_service") and fault["faulty_service"] not in services:
        services.append(fault["faulty_service"])
    services = sorted(set(services))

    logs, logs_meta = parse_logs(run_dir, services)
    metrics_result = parse_metrics_from_run_dir(run_dir)
    metrics = metrics_result["per_service"]
    metrics_meta = {
        "files_seen": metrics_result["files_seen"],
        "parse_errors": metrics_result["parse_errors"],
    }
    system, system_meta = parse_system(run_dir, services)
    traces, observed_edges, traces_meta = parse_traces(run_dir)
    metrics = derive_latency(metrics, traces)
    static_services, static_edges = parse_static_topology(run_dir, services)
    services = sorted(set(services) | set(static_services))
    workload = parse_workload_from_traces(traces)
    graph = build_graph(services, metrics, logs, system, traces, observed_edges, static_edges)
    graph_services = sorted(graph["nodes"].keys())
    graph_view = {"services": graph_services, "edges": graph["edges"]}
    rca = build_rca_features(metrics, logs, traces, system, fault)
    service_health = infer_service_health(services, system, logs, traces, rca)

    # Pull in ground_truth.json and fault_timing.json generated by gen_and_telmetry.py
    ground_truth = read_json(run_dir / "ground_truth.json") or {}
    fault_timing  = read_json(run_dir / "fault_timing.json") or {}

    import history_parser
    state = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "scenario_id": fault.get("problem_id") or run_dir.name,
        "run_dir": str(run_dir),
        "state_type": "full_scale_aiops_state_abstraction_v2",
        "fault_context": fault,
        "ground_truth": ground_truth,
        "fault_timing": fault_timing,
        "services": services,
        "metrics": metrics,
        "logs": logs,
        "traces": traces,
        "system": system,
        "workload": workload,
        "graph": graph_view,
        "history": history_parser.parse_history(run_dir),
        "service_health": service_health,
        "rca_features": rca,
        "observability_metadata": {
            "logs": logs_meta,
            "metrics": metrics_meta,
            "traces": traces_meta,
            "system": system_meta,
        },
    }
    state["sla"] = evaluate_sla(state)
    return state, graph


def build_and_write(run_dir, output_dir=None):
    run_dir = Path(run_dir)
    output_dir = Path(output_dir) if output_dir else run_dir / "processed_state"
    ensure_dir(output_dir)
    state, graph = build_state(run_dir)
    write_json(state, output_dir / "state_abstraction.json")
    write_jsonl([state], output_dir / "states.jsonl")
    write_json(graph, output_dir / "graph.json")
    rca_out = state["rca_features"]
    sla_out = state["sla"]
    obs = state["observability_metadata"]
    summary = {
        "num_snapshots": 1,
        "scenario_id": state["scenario_id"],
        "services": state["services"],
        "num_services": len(state["services"]),
        "task": state["fault_context"].get("task"),
        "fault_family": state["fault_context"].get("fault_family"),
        "faulty_service": state["fault_context"].get("faulty_service"),
        "ground_truth_answer": state["ground_truth"].get("answer"),
        "categories_present": [
            k for k in ["metrics", "logs", "traces", "system", "workload", "graph", "history"]
            if state.get(k)
        ],
        "most_suspicious_service": rca_out.get("most_suspicious_service"),
        "rca_confidence": rca_out.get("confidence"),
        "dominant_error_family": rca_out.get("dominant_error_family"),
        "observability_gaps": rca_out.get("observability_gaps"),
        "sla_violated": sla_out.get("violated", False),
        "num_unhealthy_services": sla_out.get("global_sla", {}).get("num_unhealthy_services", 0),
        "log_files_parsed": obs["logs"].get("files_parsed", 0),
        "metric_files_parsed": obs["metrics"].get("files_seen", 0),
        "trace_edges_found": obs["traces"].get("edges_found", 0),
    }
    write_json(summary, output_dir / "state_summary.json")
    print(f"[OK] wrote state to {output_dir / 'state_abstraction.json'}")
    print(f"[OK] wrote states jsonl to {output_dir / 'states.jsonl'}")
    print(f"[OK] wrote graph to {output_dir / 'graph.json'}")
    return state


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_dir", required=True)
    ap.add_argument("--output_dir", default=None)
    args = ap.parse_args()
    build_and_write(args.run_dir, args.output_dir)

if __name__ == "__main__":
    main()
