from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

from .schemas import CANONICAL_FAULT_TYPES, normalize_fault_type, parse_fault_lines


_SYSTEM_PROMPT = """\
You are a fixed RCA solver for Kubernetes/AIOps incidents.

You receive:
1. A redacted incident state abstraction.
2. A high-signal evidence summary extracted from that redacted state.
3. An instruction generated by an RCA prompt policy.

Your task is to identify the true upstream root cause service(s), not downstream victims.

Output contract:
- Output ONLY root-cause lines.
- One root cause per line.
- Each line must be exactly: service::fault_type
- service must be one of the observed service names when possible.
- fault_type must be one of:
  infra_failure, auth_failure, dependency_failure, resource_exhaustion,
  latency_degradation, network_failure, config_error, unknown
- No prose, no markdown, no JSON, no bullets, no explanations.

Diagnosis rules:
- Default to ONE root cause unless the evidence explicitly shows independent faults in unrelated services.
- Do not blame downstream victims just because they log errors.
- Do not blame helper/observability/proxy services such as jaeger or nginx-thrift unless they are directly unhealthy.
- Prefer direct service-health evidence over noisy log fan-out.
- If pods are Pending/CrashLooping/unready, nodeName is invalid, or scheduling is impossible, use infra_failure.
- If evidence mentions auth, unauthorized, credentials, permission, or MongoDB auth problems, use auth_failure.
- If target ports, service ports, connection refused due to service config, or endpoint/service misconfiguration dominates, use config_error.
- If latency/delay dominates, use latency_degradation.
- If packet loss/network unreachable dominates, use network_failure.
- Use dependency_failure only when an external dependency is unhealthy and the evidence does not indicate auth/config/network/infra.
"""


_HELPER_SERVICE_PATTERNS = (
    "jaeger",
    "nginx-thrift",
    "zipkin",
    "prometheus",
    "grafana",
    "loadgenerator",
)


class LLMRCASolver:
    """Fixed LLM RCA solver used behind the prompt-policy/controller.

    The trainable/optimizable object remains the RCA instruction policy. This
    solver is fixed at rollout time: it consumes the policy-generated instruction
    and the redacted/compressed state, then returns strict service::fault_type
    predictions. The implementation supports optional local JSONL caching to keep
    repeated smoke runs from re-calling the API.
    """

    def __init__(
        self,
        provider: str = "openai",
        model: str | None = None,
        max_tokens: int = 300,
        temperature: float = 0.0,
        state_char_budget: int = 24000,
        cache_path: str | None = None,
        max_root_causes: int = 1,
    ):
        self.provider = provider
        self.model = model
        self.max_tokens = int(max_tokens)
        self.temperature = float(temperature)
        self.state_char_budget = int(state_char_budget)
        self.max_root_causes = max(1, int(max_root_causes))
        self.cache_path = Path(cache_path).expanduser() if cache_path else None
        self._cache: dict[str, str] = {}
        if self.cache_path and self.cache_path.exists():
            self._load_cache()

        # Lazy import so offline heuristic runs do not require API packages.
        from agents.llm_client import LLMClient

        self.client = LLMClient(provider=provider, model=model)
        self.model_name = self.client.model

    def solve(self, compressed_state: dict[str, Any], instruction: str) -> str:
        cache_key = _stable_hash({
            "provider": self.provider,
            "model": self.model_name,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "max_root_causes": self.max_root_causes,
            "instruction": instruction,
            "state_hash": _stable_hash(compact_state_for_llm(compressed_state, self.state_char_budget)),
        })
        if cache_key in self._cache:
            return self._cache[cache_key]

        user_prompt = self._build_user_prompt(compressed_state, instruction)
        raw = self.client.call(
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
        )
        cleaned = sanitize_rca_prediction(raw, compressed_state, max_root_causes=self.max_root_causes)
        self._cache[cache_key] = cleaned
        self._append_cache(cache_key, cleaned, raw)
        return cleaned

    def _build_user_prompt(self, compressed_state: dict[str, Any], instruction: str) -> str:
        compact = compact_state_for_llm(compressed_state, char_budget=self.state_char_budget)
        payload = {
            "policy_instruction": instruction,
            "root_cause_count_instruction": f"Return at most {self.max_root_causes} root cause line(s). Use fewer if only one upstream cause is supported.",
            "redacted_state_abstraction": compact,
            "output_contract": "Return only service::fault_type lines. No prose.",
        }
        return json.dumps(payload, sort_keys=True, default=str)

    def _load_cache(self) -> None:
        assert self.cache_path is not None
        with self.cache_path.open("r", encoding="utf-8") as f:
            for raw in f:
                if not raw.strip():
                    continue
                try:
                    row = json.loads(raw)
                except Exception:
                    continue
                key = row.get("key")
                pred = row.get("prediction")
                if key and isinstance(pred, str):
                    self._cache[str(key)] = pred

    def _append_cache(self, key: str, prediction: str, raw_response: str) -> None:
        if not self.cache_path:
            return
        self.cache_path.parent.mkdir(parents=True, exist_ok=True)
        row = {
            "key": key,
            "provider": self.provider,
            "model": self.model_name,
            "max_root_causes": self.max_root_causes,
            "prediction": prediction,
            "raw_response": raw_response,
        }
        with self.cache_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(row, sort_keys=True, default=str) + "\n")


def compact_state_for_llm(compressed_state: dict[str, Any], char_budget: int = 24000) -> dict[str, Any]:
    """Build a compact redacted state for an LLM RCA solver.

    The function intentionally uses only the compressed state. It excludes
    scenario_id because generated scenario IDs can encode fault labels. It
    prioritizes direct service health, graph/trace/log/metric summaries, and a
    high-signal RCA evidence summary before including larger raw maps.
    """
    evidence = high_signal_evidence_summary(compressed_state)
    keys = [
        "namespace",
        "services",
        "service_health",
        "health",
        "graph",
        "service_graph",
        "traces",
        "logs",
        "metrics",
        "llm_view",
        "clusters",
    ]
    compact = {k: compressed_state.get(k) for k in keys if k in compressed_state}
    compact = {"high_signal_evidence": evidence, **compact}
    text = json.dumps(compact, sort_keys=True, default=str)
    if len(text) <= char_budget:
        return compact

    # Fallback: keep high-signal summaries first, then truncate large maps.
    services = compressed_state.get("services", []) or []
    system = compressed_state.get("system", {}) or {}
    slim_system: dict[str, Any] = {}
    for svc in services[:120]:
        info = system.get(svc, {}) if isinstance(system, dict) else {}
        if isinstance(info, dict):
            health = info.get("health") or {}
            if _is_interesting_health(health):
                slim_system[str(svc)] = {
                    "health": health,
                    "summary": info.get("summary"),
                }
    compact2 = {
        "high_signal_evidence": evidence,
        "namespace": compressed_state.get("namespace"),
        "services": services[:160],
        "interesting_system_health": slim_system,
        "graph": compressed_state.get("graph"),
        "llm_view": compressed_state.get("llm_view"),
        "clusters": compressed_state.get("clusters"),
    }
    text2 = json.dumps(compact2, sort_keys=True, default=str)
    if len(text2) <= char_budget:
        return compact2

    compact2["_truncated_note"] = f"state truncated to approximately {char_budget} chars for LLM RCA solver"
    encoded = json.dumps(compact2, sort_keys=True, default=str)[:char_budget]
    return {"truncated_json_prefix": encoded, "_truncated_note": compact2["_truncated_note"]}


def high_signal_evidence_summary(compressed_state: dict[str, Any]) -> dict[str, Any]:
    system = compressed_state.get("system", {}) or {}
    services = [str(s) for s in (compressed_state.get("services", []) or [])]
    llm_view = compressed_state.get("llm_view", {}) or {}

    direct_health: list[dict[str, Any]] = []
    if isinstance(system, dict):
        for svc, info in system.items():
            if not isinstance(info, dict):
                continue
            health = info.get("health", {}) or {}
            if _is_interesting_health(health):
                direct_health.append({
                    "service": str(svc),
                    "health": health,
                    "root_cause_signal_score": _health_signal_score(health),
                })
    direct_health.sort(key=lambda x: float(x.get("root_cause_signal_score", 0.0)), reverse=True)

    signature = _symptom_signature_fallback(compressed_state)
    service_mentions = Counter()
    for field in [
        "degraded_services",
        "top_error_services",
        "trace_sources",
        "trace_targets",
        "metric_anomaly_services",
        "affected_services",
    ]:
        for svc in signature.get(field, []) or []:
            service_mentions[str(svc)] += 1
    for edge in signature.get("failed_edges", []) or []:
        for part in str(edge).split("->"):
            if part:
                service_mentions[part] += 1

    return {
        "root_cause_ranking_hint": [
            "Prefer direct_health_services first.",
            "Then use symptom_signature and service_mention_counts to distinguish root cause from fan-out victims.",
            "Avoid helper services unless they appear in direct_health_services.",
        ],
        "direct_health_services": direct_health[:30],
        "symptom_signature": signature,
        "service_mention_counts": service_mentions.most_common(40),
        "top_log_error_services": llm_view.get("top_log_error_services"),
        "top_metric_anomaly_services": llm_view.get("top_metric_anomaly_services"),
        "observed_services_sample": services[:120],
        "helper_service_patterns_to_avoid_without_direct_health": list(_HELPER_SERVICE_PATTERNS),
        "fault_type_mapping_hints": {
            "infra_failure": "Pending/unready/crashloop/killed pods, invalid nodeName, scheduling or replica availability failures.",
            "auth_failure": "Unauthorized/auth/credential/permission failures, especially database auth revocation/missing credentials.",
            "config_error": "Bad service ports, target-port mismatch, broken deployment/service config, wrong binary/config.",
            "latency_degradation": "Delay/latency symptoms without packet loss or auth/config evidence.",
            "network_failure": "Packet loss/network unreachable/connection resets due to network fault.",
            "dependency_failure": "Only use when a dependency is unhealthy and no more specific auth/config/network/infra cause is supported.",
        },
    }


def sanitize_rca_prediction(raw: str, compressed_state: dict[str, Any] | None = None, max_root_causes: int | None = None) -> str:
    """Convert an LLM response to strict service::fault_type lines."""
    text = str(raw or "").strip()
    text = _strip_fences(text)
    lines: list[str] = []

    # Accept the intended strict format first.
    for line in text.splitlines():
        cleaned = line.strip().strip("`*->•- ").strip()
        if "::" not in cleaned:
            continue
        left, right = [x.strip() for x in cleaned.split("::", 1)]
        left = _clean_service(left)
        right = normalize_fault_type(_clean_fault_type(right))
        if left:
            lines.append(f"{left}::{right}")

    if not lines:
        # JSON fallback: tolerate {"service": ..., "fault_type": ...} or lists.
        parsed = _extract_json(text)
        lines = _lines_from_json(parsed)

    if lines:
        return _dedupe_lines(lines, compressed_state=compressed_state, max_root_causes=max_root_causes)

    # Last-resort: look for service and canonical fault type co-occurrences.
    services = []
    if compressed_state:
        services = [str(s) for s in (compressed_state.get("services", []) or [])]
    lowered = text.lower()
    for svc in services:
        if svc.lower() not in lowered:
            continue
        for ft in sorted(CANONICAL_FAULT_TYPES):
            if ft != "multifault" and ft in lowered:
                return f"{svc}::{ft}"
    return "unknown::unknown"


def _lines_from_json(parsed: Any) -> list[str]:
    out: list[str] = []
    rows = parsed if isinstance(parsed, list) else [parsed]
    for row in rows:
        if not isinstance(row, dict):
            continue
        service = row.get("service") or row.get("root_cause_service") or row.get("root_cause")
        fault_type = row.get("fault_type") or row.get("fault") or row.get("fault_family")
        if service:
            out.append(f"{_clean_service(str(service))}::{normalize_fault_type(str(fault_type or 'unknown'))}")
    return out


def _extract_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if m:
        try:
            return json.loads(m.group(1).strip())
        except Exception:
            pass
    for pattern in [r"\{[\s\S]*\}", r"\[[\s\S]*\]"]:
        m = re.search(pattern, text)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                pass
    return None


def _strip_fences(text: str) -> str:
    text = re.sub(r"^```[a-zA-Z]*\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text.strip())
    return text.strip()


def _clean_service(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"^service\s*=\s*", "", value, flags=re.IGNORECASE)
    return value.strip()


def _clean_fault_type(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"\s+#.*$", "", value)
    value = re.sub(r"\s+", "_", value)
    return value.strip()


def _dedupe_lines(
    lines: list[str],
    compressed_state: dict[str, Any] | None = None,
    max_root_causes: int | None = None,
) -> str:
    seen = set()
    candidates = []
    for line in lines:
        parsed = parse_fault_lines(line)
        if not parsed:
            continue
        label = parsed[0]
        normalized = label.canonical_key()
        if normalized in seen:
            continue
        seen.add(normalized)
        candidates.append((normalized, _prediction_priority(label.service, compressed_state)))

    if not candidates:
        return "unknown::unknown"
    candidates.sort(key=lambda x: x[1], reverse=True)
    if max_root_causes is not None:
        candidates = candidates[: max(1, int(max_root_causes))]
    return "\n".join(x[0] for x in candidates)


def _prediction_priority(service: str, compressed_state: dict[str, Any] | None) -> float:
    if not compressed_state:
        return 0.0
    svc = str(service or "")
    score = 0.0
    system = compressed_state.get("system", {}) or {}
    if isinstance(system, dict):
        health = ((system.get(svc, {}) or {}).get("health", {}) or {}) if isinstance(system.get(svc, {}), dict) else {}
        score += _health_signal_score(health) * 5.0
    signature = _symptom_signature_fallback(compressed_state)
    for field, weight in [
        ("degraded_services", 3.0),
        ("metric_anomaly_services", 2.0),
        ("top_error_services", 1.0),
        ("trace_sources", 1.0),
        ("trace_targets", 0.5),
        ("affected_services", 0.5),
    ]:
        if svc in set(str(x) for x in (signature.get(field, []) or [])):
            score += weight
    for edge in signature.get("failed_edges", []) or []:
        if svc in str(edge).split("->"):
            score += 1.5
    if _is_helper_service(svc):
        score -= 4.0
    return score


def _symptom_signature_fallback(compressed_state: dict[str, Any]) -> dict[str, Any]:
    try:
        from digital_twin_runtime.telemetry_comparator import symptom_signature

        return symptom_signature(compressed_state)
    except Exception:
        llm_view = compressed_state.get("llm_view", {}) or {}
        return {
            "degraded_services": llm_view.get("degraded_services", []) or [],
            "failed_edges": llm_view.get("failed_edges", []) or [],
            "top_error_services": [
                x.get("service") if isinstance(x, dict) else x
                for x in (llm_view.get("top_log_error_services", []) or [])
            ],
            "trace_sources": llm_view.get("trace_sources", []) or [],
            "trace_targets": llm_view.get("trace_targets", []) or [],
            "metric_anomaly_services": llm_view.get("top_metric_anomaly_services", []) or [],
            "affected_services": llm_view.get("affected_services", []) or [],
        }


def _is_interesting_health(health: Any) -> bool:
    if not isinstance(health, dict):
        return False
    status = str(health.get("status", "")).lower()
    return bool(
        health.get("infra_issue_flag")
        or float(health.get("pods_unready", 0) or 0) > 0
        or float(health.get("unavailable_replicas", 0) or 0) > 0
        or "pending" in status
        or "crash" in status
        or "no_ready" in status
        or "unready" in status
        or "error" in status
        or "failed" in status
    )


def _health_signal_score(health: Any) -> float:
    if not isinstance(health, dict):
        return 0.0
    status = str(health.get("status", "")).lower()
    score = 0.0
    score += 3.0 if health.get("infra_issue_flag") else 0.0
    score += min(3.0, float(health.get("pods_unready", 0) or 0))
    score += min(2.0, float(health.get("unavailable_replicas", 0) or 0))
    for token in ["pending", "crash", "no_ready", "unready", "failed", "error"]:
        if token in status:
            score += 1.0
    return score


def _is_helper_service(service: str) -> bool:
    s = str(service or "").lower()
    return any(pat in s for pat in _HELPER_SERVICE_PATTERNS)


def _stable_hash(obj: Any) -> str:
    blob = json.dumps(obj, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:24]
