from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from .schemas import CANONICAL_FAULT_TYPES, normalize_fault_type, parse_fault_lines


_SYSTEM_PROMPT = """\
You are a fixed RCA solver for Kubernetes/AIOps incidents.

You receive:
1. A redacted incident state abstraction.
2. An instruction generated by an RCA prompt policy.

Your task is to identify the true upstream root cause service(s), not downstream victims.

Output contract:
- Output ONLY root-cause lines.
- One root cause per line.
- Each line must be exactly: service::fault_type
- service must be one of the observed service names when possible.
- fault_type must be one of:
  infra_failure, auth_failure, dependency_failure, resource_exhaustion,
  latency_degradation, network_failure, config_error, unknown
- No prose, no markdown, no JSON, no bullets, no explanations.

For multifault incidents, output multiple service::fault_type lines.
For single-fault incidents, output one line.
"""


class LLMRCASolver:
    """Fixed LLM RCA solver used behind the prompt-policy/controller.

    The trainable/optimizable object remains the RCA instruction policy. This
    solver is fixed at rollout time: it consumes the policy-generated instruction
    and the redacted/compressed state, then returns strict service::fault_type
    predictions. The implementation supports optional local JSONL caching to keep
    repeated smoke runs from re-calling the API.
    """

    def __init__(
        self,
        provider: str = "openai",
        model: str | None = None,
        max_tokens: int = 300,
        temperature: float = 0.0,
        state_char_budget: int = 24000,
        cache_path: str | None = None,
    ):
        self.provider = provider
        self.model = model
        self.max_tokens = int(max_tokens)
        self.temperature = float(temperature)
        self.state_char_budget = int(state_char_budget)
        self.cache_path = Path(cache_path).expanduser() if cache_path else None
        self._cache: dict[str, str] = {}
        if self.cache_path and self.cache_path.exists():
            self._load_cache()

        # Lazy import so offline heuristic runs do not require API packages.
        from agents.llm_client import LLMClient

        self.client = LLMClient(provider=provider, model=model)
        self.model_name = self.client.model

    def solve(self, compressed_state: dict[str, Any], instruction: str) -> str:
        cache_key = _stable_hash({
            "provider": self.provider,
            "model": self.model_name,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "instruction": instruction,
            "state_hash": _stable_hash(compressed_state),
        })
        if cache_key in self._cache:
            return self._cache[cache_key]

        user_prompt = self._build_user_prompt(compressed_state, instruction)
        raw = self.client.call(
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
        )
        cleaned = sanitize_rca_prediction(raw, compressed_state)
        self._cache[cache_key] = cleaned
        self._append_cache(cache_key, cleaned, raw)
        return cleaned

    def _build_user_prompt(self, compressed_state: dict[str, Any], instruction: str) -> str:
        compact = compact_state_for_llm(compressed_state, char_budget=self.state_char_budget)
        payload = {
            "policy_instruction": instruction,
            "redacted_state_abstraction": compact,
            "output_contract": "Return only service::fault_type lines. No prose.",
        }
        return json.dumps(payload, sort_keys=True, default=str)

    def _load_cache(self) -> None:
        assert self.cache_path is not None
        with self.cache_path.open("r", encoding="utf-8") as f:
            for raw in f:
                if not raw.strip():
                    continue
                try:
                    row = json.loads(raw)
                except Exception:
                    continue
                key = row.get("key")
                pred = row.get("prediction")
                if key and isinstance(pred, str):
                    self._cache[str(key)] = pred

    def _append_cache(self, key: str, prediction: str, raw_response: str) -> None:
        if not self.cache_path:
            return
        self.cache_path.parent.mkdir(parents=True, exist_ok=True)
        row = {
            "key": key,
            "provider": self.provider,
            "model": self.model_name,
            "prediction": prediction,
            "raw_response": raw_response,
        }
        with self.cache_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(row, sort_keys=True, default=str) + "\n")


def compact_state_for_llm(compressed_state: dict[str, Any], char_budget: int = 24000) -> dict[str, Any]:
    """Build a compact redacted state for an LLM RCA solver.

    The function intentionally uses only the compressed state. It prioritizes
    service health, graph/trace/log/metric summaries, and llm_view fields that are
    already agent-visible.
    """
    keys = [
        "scenario_id",
        "namespace",
        "services",
        "system",
        "service_health",
        "health",
        "graph",
        "service_graph",
        "traces",
        "logs",
        "metrics",
        "llm_view",
        "clusters",
    ]
    compact = {k: compressed_state.get(k) for k in keys if k in compressed_state}
    text = json.dumps(compact, sort_keys=True, default=str)
    if len(text) <= char_budget:
        return compact

    # Fallback: keep high-signal summaries first, then truncate large maps.
    services = compressed_state.get("services", []) or []
    system = compressed_state.get("system", {}) or {}
    slim_system: dict[str, Any] = {}
    for svc in services[:120]:
        info = system.get(svc, {}) if isinstance(system, dict) else {}
        if isinstance(info, dict):
            slim_system[str(svc)] = {
                "health": info.get("health"),
                "summary": info.get("summary"),
            }
    compact2 = {
        "scenario_id": compressed_state.get("scenario_id"),
        "namespace": compressed_state.get("namespace"),
        "services": services[:160],
        "system": slim_system,
        "graph": compressed_state.get("graph"),
        "llm_view": compressed_state.get("llm_view"),
        "clusters": compressed_state.get("clusters"),
    }
    text2 = json.dumps(compact2, sort_keys=True, default=str)
    if len(text2) <= char_budget:
        return compact2

    compact2["_truncated_note"] = f"state truncated to approximately {char_budget} chars for LLM RCA solver"
    encoded = json.dumps(compact2, sort_keys=True, default=str)[:char_budget]
    return {"truncated_json_prefix": encoded, "_truncated_note": compact2["_truncated_note"]}


def sanitize_rca_prediction(raw: str, compressed_state: dict[str, Any] | None = None) -> str:
    """Convert an LLM response to strict service::fault_type lines."""
    text = str(raw or "").strip()
    text = _strip_fences(text)
    lines: list[str] = []

    # Accept the intended strict format first.
    for line in text.splitlines():
        cleaned = line.strip().strip("`*->•- ").strip()
        if "::" not in cleaned:
            continue
        left, right = [x.strip() for x in cleaned.split("::", 1)]
        left = _clean_service(left)
        right = normalize_fault_type(_clean_fault_type(right))
        if left:
            lines.append(f"{left}::{right}")

    if lines:
        return _dedupe_lines(lines)

    # JSON fallback: tolerate {"service": ..., "fault_type": ...} or lists.
    parsed = _extract_json(text)
    json_lines = _lines_from_json(parsed)
    if json_lines:
        return _dedupe_lines(json_lines)

    # Last-resort: look for service and canonical fault type co-occurrences.
    services = []
    if compressed_state:
        services = [str(s) for s in (compressed_state.get("services", []) or [])]
    lowered = text.lower()
    for svc in services:
        if svc.lower() not in lowered:
            continue
        for ft in sorted(CANONICAL_FAULT_TYPES):
            if ft != "multifault" and ft in lowered:
                return f"{svc}::{ft}"
    return "unknown::unknown"


def _lines_from_json(parsed: Any) -> list[str]:
    out: list[str] = []
    rows = parsed if isinstance(parsed, list) else [parsed]
    for row in rows:
        if not isinstance(row, dict):
            continue
        service = row.get("service") or row.get("root_cause_service") or row.get("root_cause")
        fault_type = row.get("fault_type") or row.get("fault") or row.get("fault_family")
        if service:
            out.append(f"{_clean_service(str(service))}::{normalize_fault_type(str(fault_type or 'unknown'))}")
    return out


def _extract_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if m:
        try:
            return json.loads(m.group(1).strip())
        except Exception:
            pass
    for pattern in [r"\{[\s\S]*\}", r"\[[\s\S]*\]"]:
        m = re.search(pattern, text)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                pass
    return None


def _strip_fences(text: str) -> str:
    text = re.sub(r"^```[a-zA-Z]*\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text.strip())
    return text.strip()


def _clean_service(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"^service\s*=\s*", "", value, flags=re.IGNORECASE)
    return value.strip()


def _clean_fault_type(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"\s+#.*$", "", value)
    value = re.sub(r"\s+", "_", value)
    return value.strip()


def _dedupe_lines(lines: list[str]) -> str:
    seen = set()
    out = []
    for line in lines:
        parsed = parse_fault_lines(line)
        if not parsed:
            continue
        normalized = parsed[0].canonical_key()
        if normalized not in seen:
            seen.add(normalized)
            out.append(normalized)
    return "\n".join(out) if out else "unknown::unknown"


def _stable_hash(obj: Any) -> str:
    blob = json.dumps(obj, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:24]
