from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

from .schemas import CANONICAL_FAULT_TYPES, normalize_fault_type, parse_fault_lines


_SYSTEM_PROMPT = """\
You are a fixed RCA solver for Kubernetes/AIOps incidents.

You receive:
1. A redacted incident state abstraction.
2. A high-signal evidence summary extracted from that redacted state.
3. An instruction generated by an RCA prompt policy.

Your task is to identify the true upstream root cause service(s), not downstream victims.

Output contract:
- Output ONLY root-cause lines.
- One root cause per line.
- Each line must be exactly: service::fault_type
- service must be one of the observed service names when possible.
- fault_type must be one of:
  infra_failure, auth_failure, dependency_failure, resource_exhaustion,
  latency_degradation, network_failure, config_error, unknown
- No prose, no markdown, no JSON, no bullets, no explanations.

Diagnosis rules:
- Default to ONE root cause unless the evidence explicitly shows independent faults in unrelated services.
- Use candidate_root_causes as an evidence shortlist and prefer top candidates when supported.
- Do not blame downstream victims just because they log errors.
- Do not blame helper/observability/proxy services such as jaeger or nginx-thrift unless they are directly unhealthy.
- Prefer direct service-health evidence over noisy log fan-out.
- If pods are Pending/CrashLooping/unready, nodeName is invalid, scheduling fails, or replicas are unavailable, use infra_failure.
- If auth/unauthorized/credential/permission/MongoDB auth evidence dominates, use auth_failure.
- If target ports, service ports, endpoint/service mismatch, or app config dominates, use config_error.
- If latency/delay dominates, use latency_degradation.
- If packet loss/network unreachable dominates, use network_failure.
- Use dependency_failure only when a dependency is unhealthy and no more specific auth/config/network/infra cause is supported.
"""


_HELPER_SERVICE_PATTERNS = (
    "jaeger",
    "nginx-thrift",
    "zipkin",
    "prometheus",
    "grafana",
    "loadgenerator",
)

_SERVICE_VALUE_KEYS = {
    "service", "service_name", "service_name_short", "source_service", "target_service",
    "src_service", "dst_service", "destination_service", "source", "target", "src", "dst",
    "component", "app", "workload", "deployment", "pod", "container", "name",
}

_SINGLE_WORD_SERVICE_HINTS = {
    "geo", "rate", "profile", "recommendation", "reservation", "user", "search", "frontend",
    "compose", "home", "media", "post", "text", "unique", "url",
}

_INFRA_TOKENS = (
    "pending", "crashloop", "crash", "killed", "kill", "unready", "not ready", "no ready",
    "unavailable", "node", "nodename", "schedule", "scheduling", "replica", "oom", "evicted",
)
_AUTH_TOKENS = (
    "auth", "unauthorized", "not authorized", "credential", "permission", "forbidden", "access denied",
    "authentication", "login", "password", "token",
)
_CONFIG_TOKENS = (
    "target_port", "target port", "port_misconfig", "misconfig", "wrong bin", "wrong_bin",
    "config", "configuration", "endpoint", "service port", "connection refused", "bad gateway",
)
_LATENCY_TOKENS = ("delay", "latency", "slow", "timeout", "timed out", "p99", "p95")
_NETWORK_TOKENS = ("packet", "loss", "network", "unreachable", "reset", "dropped", "drop")
_ERROR_TOKENS = ("error", "exception", "failed", "failure", "unhealthy", "degraded")


class LLMRCASolver:
    """Fixed LLM RCA solver used behind the prompt-policy/controller.

    The trainable/optimizable object remains the RCA instruction policy. This
    solver is fixed at rollout time: it consumes the policy-generated instruction
    and the redacted/compressed state, then returns strict service::fault_type
    predictions. Debug JSONL rows are written for every non-cached API call.
    """

    def __init__(
        self,
        provider: str = "openai",
        model: str | None = None,
        max_tokens: int = 300,
        temperature: float = 0.0,
        state_char_budget: int = 24000,
        cache_path: str | None = None,
        max_root_causes: int = 1,
    ):
        self.provider = provider
        self.model = model
        self.max_tokens = int(max_tokens)
        self.temperature = float(temperature)
        self.state_char_budget = int(state_char_budget)
        self.max_root_causes = max(1, int(max_root_causes))
        self.cache_path = Path(cache_path).expanduser() if cache_path else None
        self.debug_path = _default_debug_path(self.cache_path)
        self._cache: dict[str, str] = {}
        if self.cache_path and self.cache_path.exists():
            self._load_cache()

        from agents.llm_client import LLMClient

        self.client = LLMClient(provider=provider, model=model)
        self.model_name = self.client.model

    def solve(self, compressed_state: dict[str, Any], instruction: str) -> str:
        compact = compact_state_for_llm(compressed_state, char_budget=self.state_char_budget)
        cache_key = _stable_hash({
            "provider": self.provider,
            "model": self.model_name,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "max_root_causes": self.max_root_causes,
            "instruction": instruction,
            "state_hash": _stable_hash(compact),
        })
        if cache_key in self._cache:
            return self._cache[cache_key]

        user_prompt = self._build_user_prompt(compact, instruction)
        raw = self.client.call(
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            max_tokens=self.max_tokens,
            temperature=self.temperature,
        )
        sanitized_unlimited = sanitize_rca_prediction(raw, compressed_state, max_root_causes=None)
        cleaned = sanitize_rca_prediction(raw, compressed_state, max_root_causes=self.max_root_causes)
        evidence = compact.get("high_signal_evidence") if isinstance(compact, dict) else None
        debug = {
            "key": cache_key,
            "provider": self.provider,
            "model": self.model_name,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "max_root_causes": self.max_root_causes,
            "state_hash": _stable_hash(compact),
            "instruction": instruction,
            "raw_response": raw,
            "sanitized_unlimited": sanitized_unlimited,
            "sanitized_prediction": cleaned,
            "postprocess_mode": "sanitize_only_no_candidate_override",
            "high_signal_evidence": evidence,
            "candidate_root_causes": (evidence or {}).get("candidate_root_causes") if isinstance(evidence, dict) else None,
        }
        self._cache[cache_key] = cleaned
        self._append_cache(cache_key, cleaned, raw)
        self._append_debug(debug)
        return cleaned

    def _build_user_prompt(self, compact_state: dict[str, Any], instruction: str) -> str:
        payload = {
            "policy_instruction": instruction,
            "root_cause_count_instruction": f"Return at most {self.max_root_causes} root cause line(s). Use fewer if only one upstream cause is supported.",
            "redacted_state_abstraction": compact_state,
            "output_contract": "Return only service::fault_type lines. No prose.",
        }
        return json.dumps(payload, sort_keys=True, default=str)

    def _load_cache(self) -> None:
        assert self.cache_path is not None
        with self.cache_path.open("r", encoding="utf-8") as f:
            for raw in f:
                if not raw.strip():
                    continue
                try:
                    row = json.loads(raw)
                except Exception:
                    continue
                key = row.get("key")
                pred = row.get("prediction")
                if key and isinstance(pred, str):
                    self._cache[str(key)] = pred

    def _append_cache(self, key: str, prediction: str, raw_response: str) -> None:
        if not self.cache_path:
            return
        self.cache_path.parent.mkdir(parents=True, exist_ok=True)
        row = {
            "key": key,
            "provider": self.provider,
            "model": self.model_name,
            "max_root_causes": self.max_root_causes,
            "prediction": prediction,
            "raw_response": raw_response,
        }
        with self.cache_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(row, sort_keys=True, default=str) + "\n")

    def _append_debug(self, row: dict[str, Any]) -> None:
        if not self.debug_path:
            return
        self.debug_path.parent.mkdir(parents=True, exist_ok=True)
        with self.debug_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(row, sort_keys=True, default=str) + "\n")


def compact_state_for_llm(compressed_state: dict[str, Any], char_budget: int = 24000) -> dict[str, Any]:
    """Build a compact redacted state for an LLM RCA solver.

    Excludes scenario_id because generated IDs encode labels. The high-signal
    evidence extractor is recursive so it works even when telemetry is nested
    under metrics_output/logs_output/traces_output or other redacted schemas.
    """
    evidence = high_signal_evidence_summary(compressed_state)
    keys = [
        "namespace",
        "services",
        "system",
        "service_health",
        "health",
        "graph",
        "service_graph",
        "traces",
        "logs",
        "metrics",
        "llm_view",
        "clusters",
        "metrics_output",
        "logs_output",
        "traces_output",
        "workload",
    ]
    compact = {k: compressed_state.get(k) for k in keys if k in compressed_state}
    compact = {"high_signal_evidence": evidence, **compact}
    text = json.dumps(compact, sort_keys=True, default=str)
    if len(text) <= char_budget:
        return compact

    compact2 = {
        "high_signal_evidence": evidence,
        "namespace": compressed_state.get("namespace"),
        "services": evidence.get("observed_services_sample", [])[:160],
        "llm_view": compressed_state.get("llm_view"),
        "graph": compressed_state.get("graph") or compressed_state.get("service_graph"),
    }
    text2 = json.dumps(compact2, sort_keys=True, default=str)
    if len(text2) <= char_budget:
        return compact2

    compact2["_truncated_note"] = f"state truncated to approximately {char_budget} chars for LLM RCA solver"
    encoded = json.dumps(compact2, sort_keys=True, default=str)[:char_budget]
    return {"truncated_json_prefix": encoded, "_truncated_note": compact2["_truncated_note"]}


def high_signal_evidence_summary(compressed_state: dict[str, Any]) -> dict[str, Any]:
    leaf_rows = list(_iter_leaf_text(compressed_state, max_items=40000))
    services = _observed_services(compressed_state, leaf_rows)
    service_set = set(services)
    llm_view = compressed_state.get("llm_view", {}) or {}

    direct_health = _direct_health_from_system(compressed_state, service_set)
    recursive_health = _recursive_signal_rows(leaf_rows, service_set)
    direct_health.extend(recursive_health)
    direct_health = _dedupe_health_rows(direct_health)

    signature = _symptom_signature_fallback(compressed_state)
    service_mentions = Counter()
    for svc in services:
        count = 0
        svc_l = svc.lower()
        for path, text in leaf_rows:
            if svc_l in f"{path} {text}".lower():
                count += 1
        if count:
            service_mentions[svc] += count

    for field in ["degraded_services", "top_error_services", "trace_sources", "trace_targets", "metric_anomaly_services", "affected_services"]:
        for svc in signature.get(field, []) or []:
            if svc:
                service_mentions[str(svc)] += 3
    for edge in signature.get("failed_edges", []) or []:
        for part in str(edge).split("->"):
            if part:
                service_mentions[part] += 2

    text_corpus = "\n".join(f"{p}: {t}" for p, t in leaf_rows[:12000]).lower()
    candidates = build_candidate_root_causes(
        compressed_state,
        signature=signature,
        direct_health=direct_health,
        services=services,
        service_mentions=service_mentions,
        text_corpus=text_corpus,
        leaf_rows=leaf_rows,
    )
    return {
        "extractor_version": "recursive_schema_v1",
        "root_cause_ranking_hint": [
            "Prefer direct_health_services first when direct infra/pod evidence exists.",
            "Use candidate_root_causes as an evidence shortlist, not as ground truth.",
            "Use service_mention_counts and signal_by_service to avoid fan-out victims.",
            "Avoid helper/frontend/proxy services unless direct health evidence supports them.",
        ],
        "candidate_root_causes": candidates[:40],
        "direct_health_services": direct_health[:40],
        "signal_by_service": _signal_summary_by_service(leaf_rows, services)[:40],
        "symptom_signature": signature,
        "service_mention_counts": service_mentions.most_common(60),
        "top_log_error_services": llm_view.get("top_log_error_services"),
        "top_metric_anomaly_services": llm_view.get("top_metric_anomaly_services"),
        "observed_services_sample": services[:160],
        "helper_service_patterns_to_avoid_without_direct_health": list(_HELPER_SERVICE_PATTERNS),
        "fault_type_mapping_hints": {
            "infra_failure": "Pending/unready/crashloop/killed pods, invalid nodeName, scheduling or replica availability failures.",
            "auth_failure": "Unauthorized/auth/credential/permission failures, especially database auth revocation/missing credentials.",
            "config_error": "Bad service ports, target-port mismatch, broken deployment/service config, wrong binary/config.",
            "latency_degradation": "Delay/latency symptoms without packet loss or auth/config evidence.",
            "network_failure": "Packet loss/network unreachable/connection resets due to network fault.",
            "dependency_failure": "Only use when a dependency is unhealthy and no more specific auth/config/network/infra cause is supported.",
        },
    }


def build_candidate_root_causes(
    compressed_state: dict[str, Any],
    signature: dict[str, Any] | None = None,
    direct_health: list[dict[str, Any]] | None = None,
    services: list[str] | None = None,
    service_mentions: Counter | None = None,
    text_corpus: str | None = None,
    leaf_rows: list[tuple[str, str]] | None = None,
) -> list[dict[str, Any]]:
    signature = signature or _symptom_signature_fallback(compressed_state)
    direct_health = direct_health if direct_health is not None else []
    leaf_rows = leaf_rows if leaf_rows is not None else list(_iter_leaf_text(compressed_state, max_items=40000))
    services = services or _observed_services(compressed_state, leaf_rows)
    service_set = set(services)
    service_mentions = service_mentions or Counter()
    text_corpus = text_corpus if text_corpus is not None else json.dumps(compressed_state, sort_keys=True, default=str).lower()
    candidates: dict[tuple[str, str], dict[str, Any]] = {}

    def add(service: str, fault_type: str, score: float, reason: str) -> None:
        svc = str(service or "").strip()
        if not svc or svc == "unknown":
            return
        ft = normalize_fault_type(str(fault_type or "unknown"))
        key = (svc, ft)
        row = candidates.setdefault(key, {"service": svc, "fault_type": ft, "score": 0.0, "reasons": []})
        row["score"] = round(float(row["score"]) + float(score), 6)
        row["reasons"].append(reason)

    for row in direct_health:
        svc = str(row.get("service") or "")
        ft = str(row.get("suggested_fault_type") or "infra_failure")
        add(svc, ft, 4.0 + _safe_float(row.get("root_cause_signal_score")), "direct_or_recursive_health")

    for svc, count in service_mentions.most_common(80):
        if svc not in service_set and not _looks_like_service(svc):
            continue
        add(svc, "dependency_failure", min(3.0, 0.2 * count), "service_mention_frequency")

    for svc in signature.get("degraded_services", []) or []:
        add(str(svc), "infra_failure", 2.5, "degraded_service")
    for svc in signature.get("metric_anomaly_services", []) or []:
        add(str(svc), "resource_exhaustion", 2.0, "metric_anomaly")
    for svc in signature.get("top_error_services", []) or []:
        add(str(svc), "dependency_failure", 1.0, "top_log_error_service")
    for edge in signature.get("failed_edges", []) or []:
        parts = [p for p in str(edge).split("->") if p]
        if parts:
            add(parts[-1], "dependency_failure", 1.0, "failed_edge_target")
            add(parts[0], "dependency_failure", 0.5, "failed_edge_source")

    auth_hint = _has_any(text_corpus, _AUTH_TOKENS)
    config_hint = _has_any(text_corpus, _CONFIG_TOKENS)
    latency_hint = _has_any(text_corpus, _LATENCY_TOKENS)
    network_hint = _has_any(text_corpus, _NETWORK_TOKENS)
    infra_hint = _has_any(text_corpus, _INFRA_TOKENS)

    if auth_hint:
        for svc in services:
            s = svc.lower()
            if "mongo" in s or "db" in s or _service_context_has_tokens(leaf_rows, svc, _AUTH_TOKENS):
                add(svc, "auth_failure", 4.0, "auth_hint_service_context")
    if config_hint:
        for svc in services:
            if not _is_helper_service(svc) and _service_context_has_tokens(leaf_rows, svc, _CONFIG_TOKENS):
                add(svc, "config_error", 3.0, "config_hint_service_context")
    if latency_hint:
        for svc in services:
            if not _is_helper_service(svc) and _service_context_has_tokens(leaf_rows, svc, _LATENCY_TOKENS):
                add(svc, "latency_degradation", 2.0, "latency_hint_service_context")
    if network_hint:
        for svc in services:
            if not _is_helper_service(svc) and _service_context_has_tokens(leaf_rows, svc, _NETWORK_TOKENS):
                add(svc, "network_failure", 2.0, "network_hint_service_context")
    if infra_hint:
        for svc in services:
            if not _is_helper_service(svc) and _service_context_has_tokens(leaf_rows, svc, _INFRA_TOKENS):
                add(svc, "infra_failure", 2.5, "infra_hint_service_context")

    rows = []
    for row in candidates.values():
        svc = str(row["service"])
        score = float(row["score"])
        if _is_helper_service(svc):
            score -= 5.0
            row["reasons"].append("helper_service_penalty")
        if svc.endswith("-frontend") or svc in {"media-frontend", "nginx-web-server", "frontend"}:
            score -= 1.5
            row["reasons"].append("frontend_proxy_penalty")
        if svc not in service_set:
            score -= 1.0
            row["reasons"].append("not_in_observed_services_penalty")
        rows.append({**row, "score": round(score, 6)})
    rows.sort(key=lambda r: float(r.get("score", 0.0)), reverse=True)
    return rows


def sanitize_rca_prediction(raw: str, compressed_state: dict[str, Any] | None = None, max_root_causes: int | None = None) -> str:
    text = str(raw or "").strip()
    text = _strip_fences(text)
    lines: list[str] = []

    for line in text.splitlines():
        cleaned = line.strip().strip("`*->•- ").strip()
        if "::" not in cleaned:
            continue
        left, right = [x.strip() for x in cleaned.split("::", 1)]
        left = _clean_service(left)
        right = normalize_fault_type(_clean_fault_type(right))
        if left:
            lines.append(f"{left}::{right}")

    if not lines:
        parsed = _extract_json(text)
        lines = _lines_from_json(parsed)

    if lines:
        return _dedupe_lines(lines, compressed_state=compressed_state, max_root_causes=max_root_causes)

    services = _observed_services(compressed_state or {}, list(_iter_leaf_text(compressed_state or {}, max_items=8000)))
    lowered = text.lower()
    for svc in services:
        if svc.lower() not in lowered:
            continue
        for ft in sorted(CANONICAL_FAULT_TYPES):
            if ft != "multifault" and ft in lowered:
                return f"{svc}::{ft}"
    return "unknown::unknown"


def _iter_leaf_text(obj: Any, path: str = "", max_items: int = 20000):
    count = 0
    stack = [(path, obj)]
    while stack and count < max_items:
        p, v = stack.pop()
        if isinstance(v, dict):
            for k, val in list(v.items())[::-1]:
                key = str(k)
                if key == "scenario_id":
                    continue
                stack.append((f"{p}.{key}" if p else key, val))
        elif isinstance(v, list):
            for i, val in list(enumerate(v))[::-1]:
                stack.append((f"{p}[{i}]", val))
        else:
            if v is None:
                continue
            text = str(v)
            if text:
                count += 1
                yield p, text[:2000]


def _observed_services(compressed_state: dict[str, Any], leaf_rows: list[tuple[str, str]]) -> list[str]:
    services: set[str] = set()
    for key in ("services", "service_names", "all_services", "observed_services"):
        vals = compressed_state.get(key)
        if isinstance(vals, list):
            services.update(str(x) for x in vals if _looks_like_service(str(x)))
    system = compressed_state.get("system") or {}
    if isinstance(system, dict):
        services.update(str(k) for k in system.keys() if _looks_like_service(str(k)))

    for path, text in leaf_rows:
        path_l = path.lower()
        last_key = path_l.rsplit(".", 1)[-1].split("[", 1)[0]
        if last_key in _SERVICE_VALUE_KEYS or "service" in path_l or "pod" in path_l or "deployment" in path_l:
            for svc in _service_names_from_text(text):
                services.add(svc)
        for svc in _service_names_from_text(path):
            services.add(svc)
        for svc in _service_names_from_text(text):
            if "-" in svc or svc in _SINGLE_WORD_SERVICE_HINTS:
                services.add(svc)
    return sorted(s for s in services if _looks_like_service(s))


def _service_names_from_text(text: str) -> set[str]:
    out = set()
    for m in re.finditer(r"\b[a-z][a-z0-9]*(?:-[a-z0-9]+)*\b", str(text).lower()):
        token = m.group(0).strip("-_")
        if _looks_like_service(token):
            out.add(token)
    return out


def _looks_like_service(token: str) -> bool:
    t = str(token or "").strip().lower()
    if not t or len(t) < 3:
        return False
    deny = {
        "default", "true", "false", "none", "null", "namespace", "service", "services", "pod", "pods",
        "metrics", "metric", "logs", "log", "trace", "traces", "output", "status", "health", "error",
        "warning", "failed", "success", "normal", "unknown", "node", "name", "type", "value",
    }
    if t in deny:
        return False
    if any(ch.isdigit() for ch in t) and not ("-" in t or "mongo" in t):
        return False
    if "-" in t:
        return True
    if t in _SINGLE_WORD_SERVICE_HINTS:
        return True
    if "mongo" in t or t.endswith("db"):
        return True
    return False


def _direct_health_from_system(compressed_state: dict[str, Any], service_set: set[str]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    system = compressed_state.get("system", {}) or {}
    if isinstance(system, dict):
        for svc, info in system.items():
            if not isinstance(info, dict):
                continue
            health = info.get("health", {}) or {}
            if _is_interesting_health(health):
                rows.append({
                    "service": str(svc),
                    "health": health,
                    "suggested_fault_type": _suggest_fault_from_text(json.dumps(health, sort_keys=True, default=str)),
                    "root_cause_signal_score": _health_signal_score(health),
                    "source": "system.health",
                })
    return rows


def _recursive_signal_rows(leaf_rows: list[tuple[str, str]], service_set: set[str]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for svc in service_set:
        context = _service_context(leaf_rows, svc, max_rows=25)
        if not context:
            continue
        joined = "\n".join(f"{p}: {t}" for p, t in context).lower()
        if not _has_any(joined, _INFRA_TOKENS + _AUTH_TOKENS + _CONFIG_TOKENS + _LATENCY_TOKENS + _NETWORK_TOKENS + _ERROR_TOKENS):
            continue
        rows.append({
            "service": svc,
            "health": {"evidence_excerpt": context[:8]},
            "suggested_fault_type": _suggest_fault_from_text(joined),
            "root_cause_signal_score": _text_signal_score(joined),
            "source": "recursive_text_context",
        })
    rows.sort(key=lambda x: float(x.get("root_cause_signal_score", 0.0)), reverse=True)
    return rows


def _signal_summary_by_service(leaf_rows: list[tuple[str, str]], services: list[str]) -> list[dict[str, Any]]:
    out = []
    for svc in services:
        context = _service_context(leaf_rows, svc, max_rows=30)
        joined = "\n".join(f"{p}: {t}" for p, t in context).lower()
        if not joined:
            continue
        counts = {
            "infra": _token_count(joined, _INFRA_TOKENS),
            "auth": _token_count(joined, _AUTH_TOKENS),
            "config": _token_count(joined, _CONFIG_TOKENS),
            "latency": _token_count(joined, _LATENCY_TOKENS),
            "network": _token_count(joined, _NETWORK_TOKENS),
            "error": _token_count(joined, _ERROR_TOKENS),
        }
        score = sum(counts.values())
        if score:
            out.append({"service": svc, "signal_counts": counts, "score": score, "evidence_excerpt": context[:5]})
    out.sort(key=lambda r: float(r.get("score", 0.0)), reverse=True)
    return out


def _service_context(leaf_rows: list[tuple[str, str]], service: str, max_rows: int = 20) -> list[tuple[str, str]]:
    svc = service.lower()
    out = []
    for path, text in leaf_rows:
        hay = f"{path} {text}".lower()
        if svc in hay:
            out.append((path, text[:400]))
            if len(out) >= max_rows:
                break
    return out


def _service_context_has_tokens(leaf_rows: list[tuple[str, str]], service: str, tokens: tuple[str, ...]) -> bool:
    joined = "\n".join(f"{p}: {t}" for p, t in _service_context(leaf_rows, service, max_rows=40)).lower()
    return _has_any(joined, tokens)


def _dedupe_health_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    best: dict[tuple[str, str], dict[str, Any]] = {}
    for row in rows:
        key = (str(row.get("service") or ""), str(row.get("suggested_fault_type") or "unknown"))
        if key not in best or _safe_float(row.get("root_cause_signal_score")) > _safe_float(best[key].get("root_cause_signal_score")):
            best[key] = row
    out = list(best.values())
    out.sort(key=lambda x: float(x.get("root_cause_signal_score", 0.0)), reverse=True)
    return out


def _suggest_fault_from_text(text: str) -> str:
    t = str(text or "").lower()
    scores = {
        "auth_failure": _token_count(t, _AUTH_TOKENS) * 3.0,
        "config_error": _token_count(t, _CONFIG_TOKENS) * 2.5,
        "network_failure": _token_count(t, _NETWORK_TOKENS) * 2.0,
        "latency_degradation": _token_count(t, _LATENCY_TOKENS) * 2.0,
        "infra_failure": _token_count(t, _INFRA_TOKENS) * 2.0,
    }
    best = max(scores.items(), key=lambda kv: kv[1])
    return best[0] if best[1] > 0 else "dependency_failure"


def _text_signal_score(text: str) -> float:
    t = str(text or "").lower()
    return float(
        _token_count(t, _AUTH_TOKENS) * 3.0
        + _token_count(t, _CONFIG_TOKENS) * 2.5
        + _token_count(t, _INFRA_TOKENS) * 2.0
        + _token_count(t, _LATENCY_TOKENS) * 1.5
        + _token_count(t, _NETWORK_TOKENS) * 1.5
        + _token_count(t, _ERROR_TOKENS) * 1.0
    )


def _token_count(text: str, tokens: tuple[str, ...]) -> int:
    t = str(text or "").lower()
    return sum(t.count(tok) for tok in tokens)


def _has_any(text: str, tokens: tuple[str, ...]) -> bool:
    t = str(text or "").lower()
    return any(tok in t for tok in tokens)


def _lines_from_json(parsed: Any) -> list[str]:
    out: list[str] = []
    rows = parsed if isinstance(parsed, list) else [parsed]
    for row in rows:
        if not isinstance(row, dict):
            continue
        service = row.get("service") or row.get("root_cause_service") or row.get("root_cause")
        fault_type = row.get("fault_type") or row.get("fault") or row.get("fault_family")
        if service:
            out.append(f"{_clean_service(str(service))}::{normalize_fault_type(str(fault_type or 'unknown'))}")
    return out


def _extract_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except Exception:
        pass
    m = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if m:
        try:
            return json.loads(m.group(1).strip())
        except Exception:
            pass
    for pattern in [r"\{[\s\S]*\}", r"\[[\s\S]*\]"]:
        m = re.search(pattern, text)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                pass
    return None


def _strip_fences(text: str) -> str:
    text = re.sub(r"^```[a-zA-Z]*\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text.strip())
    return text.strip()


def _clean_service(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"^service\s*=\s*", "", value, flags=re.IGNORECASE)
    return value.strip()


def _clean_fault_type(text: str) -> str:
    value = str(text or "").strip().strip('"\'`,.;:()[]{}')
    value = re.sub(r"\s+#.*$", "", value)
    value = re.sub(r"\s+", "_", value)
    return value.strip()


def _dedupe_lines(
    lines: list[str],
    compressed_state: dict[str, Any] | None = None,
    max_root_causes: int | None = None,
) -> str:
    seen = set()
    candidates = []
    for line in lines:
        parsed = parse_fault_lines(line)
        if not parsed:
            continue
        label = parsed[0]
        normalized = label.canonical_key()
        if normalized in seen:
            continue
        seen.add(normalized)
        candidates.append((normalized, _prediction_priority(label.service, compressed_state)))

    if not candidates:
        return "unknown::unknown"
    candidates.sort(key=lambda x: x[1], reverse=True)
    if max_root_causes is not None:
        candidates = candidates[: max(1, int(max_root_causes))]
    return "\n".join(x[0] for x in candidates)


def _prediction_priority(service: str, compressed_state: dict[str, Any] | None) -> float:
    if not compressed_state:
        return 0.0
    leaf_rows = list(_iter_leaf_text(compressed_state, max_items=12000))
    svc = str(service or "")
    score = 0.0
    system = compressed_state.get("system", {}) or {}
    if isinstance(system, dict):
        health = ((system.get(svc, {}) or {}).get("health", {}) or {}) if isinstance(system.get(svc, {}), dict) else {}
        score += _health_signal_score(health) * 5.0
    signature = _symptom_signature_fallback(compressed_state)
    for field, weight in [
        ("degraded_services", 3.0),
        ("metric_anomaly_services", 2.0),
        ("top_error_services", 1.0),
        ("trace_sources", 1.0),
        ("trace_targets", 0.5),
        ("affected_services", 0.5),
    ]:
        if svc in set(str(x) for x in (signature.get(field, []) or [])):
            score += weight
    for edge in signature.get("failed_edges", []) or []:
        if svc in str(edge).split("->"):
            score += 1.5
    if _service_context_has_tokens(leaf_rows, svc, _INFRA_TOKENS + _AUTH_TOKENS + _CONFIG_TOKENS + _LATENCY_TOKENS + _NETWORK_TOKENS):
        score += 3.0
    if _is_helper_service(svc):
        score -= 4.0
    return score


def _symptom_signature_fallback(compressed_state: dict[str, Any]) -> dict[str, Any]:
    try:
        from digital_twin_runtime.telemetry_comparator import symptom_signature

        sig = symptom_signature(compressed_state)
        if any(sig.get(k) for k in ["degraded_services", "failed_edges", "top_error_services", "trace_sources", "trace_targets", "metric_anomaly_services", "affected_services"]):
            return sig
    except Exception:
        pass
    llm_view = compressed_state.get("llm_view", {}) or {}
    return {
        "degraded_services": llm_view.get("degraded_services", []) or [],
        "failed_edges": llm_view.get("failed_edges", []) or [],
        "top_error_services": [
            x.get("service") if isinstance(x, dict) else x
            for x in (llm_view.get("top_log_error_services", []) or [])
        ],
        "trace_sources": llm_view.get("trace_sources", []) or [],
        "trace_targets": llm_view.get("trace_targets", []) or [],
        "metric_anomaly_services": llm_view.get("top_metric_anomaly_services", []) or [],
        "affected_services": llm_view.get("affected_services", []) or [],
    }


def _is_interesting_health(health: Any) -> bool:
    if not isinstance(health, dict):
        return False
    status = str(health.get("status", "")).lower()
    return bool(
        health.get("infra_issue_flag")
        or _safe_float(health.get("pods_unready")) > 0
        or _safe_float(health.get("unavailable_replicas")) > 0
        or _has_any(status, _INFRA_TOKENS + _ERROR_TOKENS)
    )


def _health_signal_score(health: Any) -> float:
    if not isinstance(health, dict):
        return 0.0
    status = str(health.get("status", "")).lower()
    score = 0.0
    score += 3.0 if health.get("infra_issue_flag") else 0.0
    score += min(3.0, _safe_float(health.get("pods_unready")))
    score += min(2.0, _safe_float(health.get("unavailable_replicas")))
    score += _text_signal_score(status)
    return score


def _safe_float(x: Any, default: float = 0.0) -> float:
    try:
        return float(x)
    except Exception:
        return default


def _is_helper_service(service: str) -> bool:
    s = str(service or "").lower()
    return any(pat in s for pat in _HELPER_SERVICE_PATTERNS)


def _default_debug_path(cache_path: Path | None) -> Path | None:
    if cache_path is None:
        return None
    return cache_path.parent / "llm_rca_debug.jsonl"


def _stable_hash(obj: Any) -> str:
    blob = json.dumps(obj, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:24]
