from __future__ import annotations

"""Transactional synchronized trainer for the two-role factorized GRPO policy.

The joint rollout is causal (RCA -> twin -> Action -> recovery) but optimization
uses two independent LoRA policies on one frozen base model. A synchronized
training update therefore has the following contract:

1. consume one frozen rollout batch generated by one published policy bundle;
2. validate exact-token GRPO records for both role buffers;
3. update ``lora_rca`` only from RCA policy advantages;
4. update ``lora_action`` only from Action policy advantages;
5. publish a new bundle version only after all requested role updates succeed;
6. roll back *both* adapters and optimizer states if either role update fails.

A role with no non-zero policy advantage is skipped. In particular, a positive
KL coefficient is never allowed to create a KL-only update when the policy-gradient
signal is identically zero.
"""

import copy
import json
import os
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Sequence

import torch

from .factorized_grpo_learner import FactorizedGRPOConfig, optimizer_step
from .grpo_dataset import load_grpo_dataset, validate_grpo_sample
from .grpo_math import group_relative_advantages
from .peft_adapter_control import (
    ROLE_ADAPTERS,
    activate_exclusive_adapter,
    parameter_belongs_to_adapter,
)


ROLE_TO_ADAPTER = {
    "rca": "lora_rca",
    "action": "lora_action",
}
ROLE_TO_OPTIMIZER_ROLE = {
    "rca": "rca_policy",
    "action": "action_policy",
}


@dataclass(frozen=True)
class SynchronizedGRPOTrainerConfig:
    rca_learning_rate: float = 1e-5
    action_learning_rate: float = 1e-5
    weight_decay: float = 0.0
    signal_epsilon: float = 1e-12
    require_single_sync_batch: bool = True
    require_matching_policy_version: bool = True
    grpo: FactorizedGRPOConfig = field(default_factory=FactorizedGRPOConfig)

    def validate(self) -> None:
        if self.rca_learning_rate <= 0.0:
            raise ValueError("rca_learning_rate must be > 0")
        if self.action_learning_rate <= 0.0:
            raise ValueError("action_learning_rate must be > 0")
        if self.weight_decay < 0.0:
            raise ValueError("weight_decay must be >= 0")
        if self.signal_epsilon < 0.0:
            raise ValueError("signal_epsilon must be >= 0")
        self.grpo.validate()


def _adapter_named_parameters(model: Any, adapter_name: str) -> list[tuple[str, torch.nn.Parameter]]:
    if adapter_name not in ROLE_ADAPTERS:
        raise ValueError(f"unknown adapter {adapter_name!r}")
    rows = [
        (name, parameter)
        for name, parameter in model.named_parameters()
        if parameter_belongs_to_adapter(name, adapter_name)
    ]
    if not rows:
        raise RuntimeError(f"model contains no parameters for adapter {adapter_name!r}")
    return rows


def _snapshot_adapter_state(model: Any) -> dict[str, torch.Tensor]:
    out: dict[str, torch.Tensor] = {}
    for name, parameter in model.named_parameters():
        if any(parameter_belongs_to_adapter(name, adapter) for adapter in ROLE_ADAPTERS):
            out[name] = parameter.detach().clone()
    if not out:
        raise RuntimeError("cannot snapshot adapters: no LoRA parameters found")
    return out


def _restore_adapter_state(model: Any, state: dict[str, torch.Tensor]) -> None:
    named = dict(model.named_parameters())
    missing = [name for name in state if name not in named]
    if missing:
        raise KeyError(f"cannot restore adapter snapshot; missing parameters: {missing[:20]}")
    with torch.no_grad():
        for name, value in state.items():
            parameter = named[name]
            parameter.copy_(value.to(device=parameter.device, dtype=parameter.dtype))


def _freeze_everything(model: Any) -> None:
    if hasattr(model, "zero_grad"):
        model.zero_grad(set_to_none=True)
    for parameter in model.parameters():
        parameter.requires_grad_(False)
        parameter.grad = None


def _json_safe_config(config: SynchronizedGRPOTrainerConfig) -> dict[str, Any]:
    return asdict(config)


def _validate_factorized_group_math(rows: Sequence[dict[str, Any]]) -> None:
    """Recheck trajectory advantages and 1/D weights for in-memory callers.

    ``load_grpo_dataset`` performs these checks for JSONL input, but the trainer
    also accepts already-materialized rows.  Never let an in-memory caller bypass
    the mathematical contract.
    """
    grouped: dict[str, dict[str, list[dict[str, Any]]]] = {}
    for row in rows:
        gid = str(row.get("optimizer_group_id") or "")
        tid = str(row.get("trajectory_id") or "")
        grouped.setdefault(gid, {}).setdefault(tid, []).append(row)

    for gid, trajectories in grouped.items():
        if not gid:
            raise ValueError("optimizer_group_id must be non-empty")
        if len(trajectories) < 2:
            raise ValueError(f"{gid}: optimizer group must contain at least two complete trajectories")

        tids = sorted(trajectories)
        rewards: list[float] = []
        stored_advantages: list[float] = []
        for tid in tids:
            trows = trajectories[tid]
            if not tid:
                raise ValueError(f"{gid}: trajectory_id must be non-empty")
            expected_weight = 1.0 / float(len(trows))
            weights = [float(row["optimizer_sample_weight"]) for row in trows]
            if abs(sum(weights) - 1.0) > 1e-8:
                raise ValueError(f"{gid}/{tid}: optimizer_sample_weight values must sum to one")
            if any(abs(weight - expected_weight) > 1e-8 for weight in weights):
                raise ValueError(f"{gid}/{tid}: every decision weight must equal 1/D_role")

            reward_values = {float(row["policy_reward"]) for row in trows}
            advantage_values = {float(row["policy_advantage"]) for row in trows}
            if len(reward_values) != 1:
                raise ValueError(f"{gid}/{tid}: trajectory rows disagree on policy_reward")
            if len(advantage_values) != 1:
                raise ValueError(f"{gid}/{tid}: trajectory rows disagree on policy_advantage")
            rewards.append(next(iter(reward_values)))
            stored_advantages.append(next(iter(advantage_values)))

        recomputed = group_relative_advantages(rewards, scale_by_std=True)
        for tid, stored, expected in zip(tids, stored_advantages, recomputed.advantages):
            if abs(float(stored) - float(expected)) > 1e-5:
                raise ValueError(
                    f"{gid}/{tid}: stored policy_advantage={stored} does not match recomputed {expected}"
                )


class SynchronizedFactorizedGRPOTrainer:
    """Stateful, transactional trainer for one shared base + two LoRA adapters."""

    def __init__(
        self,
        model: Any,
        *,
        current_policy_version: str,
        config: SynchronizedGRPOTrainerConfig | None = None,
        device: torch.device | str | None = None,
    ) -> None:
        self.model = model
        self.config = config or SynchronizedGRPOTrainerConfig()
        self.config.validate()
        if not str(current_policy_version).strip():
            raise ValueError("current_policy_version must be non-empty")
        self.current_policy_version = str(current_policy_version)
        # Keep a fixed root so version strings remain O(1) length across thousands
        # of synchronized updates instead of recursively appending suffixes.
        self.policy_version_root = self.current_policy_version.split("@u", 1)[0]
        self.bundle_update_step = 0
        self.rca_update_step = 0
        self.action_update_step = 0
        if device is None:
            try:
                device = next(model.parameters()).device
            except StopIteration:
                device = torch.device("cpu")
        self.device = torch.device(device)

        rca_named = _adapter_named_parameters(model, "lora_rca")
        action_named = _adapter_named_parameters(model, "lora_action")
        rca_ids = {id(p) for _, p in rca_named}
        action_ids = {id(p) for _, p in action_named}
        if rca_ids & action_ids:
            raise AssertionError("RCA and Action optimizers would share parameter tensors")

        self._role_parameter_names = {
            "rca": [name for name, _ in rca_named],
            "action": [name for name, _ in action_named],
        }
        self.rca_optimizer = torch.optim.AdamW(
            [p for _, p in rca_named],
            lr=float(self.config.rca_learning_rate),
            weight_decay=float(self.config.weight_decay),
        )
        self.action_optimizer = torch.optim.AdamW(
            [p for _, p in action_named],
            lr=float(self.config.action_learning_rate),
            weight_decay=float(self.config.weight_decay),
        )
        _freeze_everything(self.model)
        self._assert_optimizer_partition()

    def _assert_optimizer_partition(self) -> None:
        base_ids = {
            id(parameter)
            for name, parameter in self.model.named_parameters()
            if not any(parameter_belongs_to_adapter(name, adapter) for adapter in ROLE_ADAPTERS)
        }
        rca_ids = {id(p) for group in self.rca_optimizer.param_groups for p in group["params"]}
        action_ids = {id(p) for group in self.action_optimizer.param_groups for p in group["params"]}
        if rca_ids & action_ids:
            raise AssertionError("RCA and Action optimizer parameter sets overlap")
        if base_ids & rca_ids:
            raise AssertionError("RCA optimizer contains frozen base-model parameters")
        if base_ids & action_ids:
            raise AssertionError("Action optimizer contains frozen base-model parameters")

    @staticmethod
    def _role_signal_summary(rows: Sequence[dict[str, Any]], *, epsilon: float) -> dict[str, Any]:
        groups: dict[str, dict[str, float]] = {}
        for row in rows:
            gid = str(row.get("optimizer_group_id") or "")
            tid = str(row.get("trajectory_id") or "")
            advantage = float(row.get("policy_advantage", 0.0) or 0.0)
            previous = groups.setdefault(gid, {}).get(tid)
            if previous is not None and abs(previous - advantage) > 1e-8:
                raise AssertionError(
                    f"{gid}/{tid}: rows from one trajectory disagree on policy_advantage"
                )
            groups[gid][tid] = advantage

        nonzero_groups = 0
        nonzero_trajectories = 0
        max_abs = 0.0
        for trajectories in groups.values():
            values = list(trajectories.values())
            local_nonzero = sum(abs(value) > epsilon for value in values)
            nonzero_trajectories += local_nonzero
            max_abs = max(max_abs, max((abs(value) for value in values), default=0.0))
            if local_nonzero:
                nonzero_groups += 1
        return {
            "num_optimizer_groups": len(groups),
            "nonzero_advantage_groups": nonzero_groups,
            "zero_advantage_groups": len(groups) - nonzero_groups,
            "nonzero_advantage_trajectories": nonzero_trajectories,
            "max_abs_policy_advantage": max_abs,
            "has_policy_gradient_signal": bool(nonzero_groups > 0),
        }

    def _validate_role_rows(self, rows: Sequence[dict[str, Any]], role: str) -> dict[str, Any]:
        if role not in ROLE_TO_ADAPTER:
            raise ValueError(role)
        if not rows:
            raise ValueError(f"{role} buffer is empty")
        expected_adapter = ROLE_TO_ADAPTER[role]
        expected_optimizer_role = ROLE_TO_OPTIMIZER_ROLE[role]

        versions: set[str] = set()
        sync_batches: set[str] = set()
        for index, row in enumerate(rows, start=1):
            errors = validate_grpo_sample(
                row,
                require_policy_credit=True,
                require_old_logprobs=True,
            )
            if errors:
                raise ValueError(
                    json.dumps(
                        {"role": role, "row_index": index, "sample_id": row.get("sample_id"), "errors": errors},
                        sort_keys=True,
                    )
                )
            if row.get("adapter_id") != expected_adapter:
                raise ValueError(f"{role} row has adapter_id={row.get('adapter_id')!r}")
            metadata = row.get("metadata", {}) or {}
            if metadata.get("optimizer_role") != expected_optimizer_role:
                raise ValueError(
                    f"{role} row has optimizer_role={metadata.get('optimizer_role')!r}"
                )
            versions.add(str(row.get("policy_version") or ""))
            sync_batches.add(str(row.get("sync_batch_id") or metadata.get("sync_batch_id") or ""))

        _validate_factorized_group_math(rows)

        if len(versions) != 1:
            raise ValueError(f"{role} buffer mixes policy versions: {sorted(versions)}")
        rollout_version = next(iter(versions))
        if self.config.require_matching_policy_version and rollout_version != self.current_policy_version:
            raise ValueError(
                f"stale/wrong {role} rollout: buffer policy_version={rollout_version!r}, "
                f"trainer current_policy_version={self.current_policy_version!r}"
            )
        if self.config.require_single_sync_batch:
            if len(sync_batches) != 1 or "" in sync_batches:
                raise ValueError(f"{role} buffer must contain exactly one non-empty sync_batch_id: {sorted(sync_batches)}")

        signal = self._role_signal_summary(rows, epsilon=float(self.config.signal_epsilon))
        return {
            "policy_version": rollout_version,
            "sync_batches": sorted(sync_batches),
            "num_rows": len(rows),
            "signal": signal,
        }

    def _validate_joint_batch(
        self,
        rca_rows: Sequence[dict[str, Any]],
        action_rows: Sequence[dict[str, Any]],
    ) -> dict[str, Any]:
        rca = self._validate_role_rows(rca_rows, "rca")
        action = self._validate_role_rows(action_rows, "action")
        if rca["policy_version"] != action["policy_version"]:
            raise ValueError("RCA and Action buffers were not generated by the same policy bundle version")
        if self.config.require_single_sync_batch and rca["sync_batches"] != action["sync_batches"]:
            raise ValueError(
                f"RCA/Action buffers belong to different sync batches: {rca['sync_batches']} vs {action['sync_batches']}"
            )
        return {"rca": rca, "action": action}

    def _update_role(
        self,
        role: str,
        rows: Sequence[dict[str, Any]],
        signal: dict[str, Any],
    ) -> dict[str, Any]:
        adapter_name = ROLE_TO_ADAPTER[role]
        if not signal["has_policy_gradient_signal"]:
            return {
                "role": role,
                "adapter": adapter_name,
                "updated": False,
                "skip_reason": "zero_policy_advantage_signal",
                "signal": signal,
                "kl_only_update_blocked": bool(self.config.grpo.kl_coeff > 0.0),
            }

        activate_exclusive_adapter(self.model, adapter_name)
        optimizer = self.rca_optimizer if role == "rca" else self.action_optimizer
        diagnostics = optimizer_step(
            self.model,
            optimizer,
            rows,
            config=self.config.grpo,
            device=self.device,
        )
        if role == "rca":
            self.rca_update_step += 1
        else:
            self.action_update_step += 1
        return {
            "role": role,
            "adapter": adapter_name,
            "updated": True,
            "signal": signal,
            "optimizer": diagnostics,
        }

    def update_joint_batch(
        self,
        rca_rows: Sequence[dict[str, Any]],
        action_rows: Sequence[dict[str, Any]],
    ) -> dict[str, Any]:
        """Apply one atomic synchronized update over a frozen joint rollout batch."""
        validation = self._validate_joint_batch(rca_rows, action_rows)
        old_version = self.current_policy_version

        adapter_snapshot = _snapshot_adapter_state(self.model)
        rca_optimizer_snapshot = copy.deepcopy(self.rca_optimizer.state_dict())
        action_optimizer_snapshot = copy.deepcopy(self.action_optimizer.state_dict())
        old_steps = (self.bundle_update_step, self.rca_update_step, self.action_update_step)

        try:
            rca_result = self._update_role("rca", rca_rows, validation["rca"]["signal"])
            action_result = self._update_role("action", action_rows, validation["action"]["signal"])
            any_update = bool(rca_result["updated"] or action_result["updated"])
            if any_update:
                self.bundle_update_step += 1
                self.current_policy_version = f"{self.policy_version_root}@u{self.bundle_update_step:06d}"
            _freeze_everything(self.model)
        except Exception as exc:
            _restore_adapter_state(self.model, adapter_snapshot)
            self.rca_optimizer.load_state_dict(rca_optimizer_snapshot)
            self.action_optimizer.load_state_dict(action_optimizer_snapshot)
            self.bundle_update_step, self.rca_update_step, self.action_update_step = old_steps
            self.current_policy_version = old_version
            _freeze_everything(self.model)
            raise RuntimeError(
                "synchronized GRPO update failed; both adapters and optimizer states were rolled back"
            ) from exc

        return {
            "status": "UPDATED" if any_update else "SKIPPED_ZERO_SIGNAL",
            "rollout_policy_version": old_version,
            "published_policy_version": self.current_policy_version,
            "bundle_update_step": self.bundle_update_step,
            "rca_update_step": self.rca_update_step,
            "action_update_step": self.action_update_step,
            "sync_batch_id": validation["rca"]["sync_batches"][0] if validation["rca"]["sync_batches"] else None,
            "rca": rca_result,
            "action": action_result,
            "publish_after_both_role_updates": True,
            "shared_base_optimizer_membership": False,
        }

    def update_from_jsonl(self, rca_path: str | Path, action_path: str | Path) -> dict[str, Any]:
        rca_rows = load_grpo_dataset(
            rca_path,
            require_policy_credit=True,
            require_old_logprobs=True,
        )
        action_rows = load_grpo_dataset(
            action_path,
            require_policy_credit=True,
            require_old_logprobs=True,
        )
        return self.update_joint_batch(rca_rows, action_rows)

    def save_checkpoint(self, path: str | Path, *, last_update: dict[str, Any] | None = None) -> Path:
        """Atomically save only trainable policy/optimizer state, never the frozen base."""
        target = Path(path).expanduser()
        target.parent.mkdir(parents=True, exist_ok=True)
        tmp = target.with_name(target.name + ".tmp")

        adapter_state = {
            name: tensor.detach().cpu()
            for name, tensor in _snapshot_adapter_state(self.model).items()
        }
        payload = {
            "format": "factorized_grpo_two_adapter_checkpoint_v1",
            "current_policy_version": self.current_policy_version,
            "policy_version_root": self.policy_version_root,
            "bundle_update_step": self.bundle_update_step,
            "rca_update_step": self.rca_update_step,
            "action_update_step": self.action_update_step,
            "trainer_config": _json_safe_config(self.config),
            "role_parameter_names": self._role_parameter_names,
            "adapter_state": adapter_state,
            "rca_optimizer_state": self.rca_optimizer.state_dict(),
            "action_optimizer_state": self.action_optimizer.state_dict(),
            "last_update": last_update,
        }
        torch.save(payload, tmp)
        os.replace(tmp, target)
        return target

    def load_checkpoint(self, path: str | Path) -> dict[str, Any]:
        source = Path(path).expanduser()
        payload = torch.load(source, map_location=self.device, weights_only=False)
        if payload.get("format") != "factorized_grpo_two_adapter_checkpoint_v1":
            raise ValueError("unsupported synchronized trainer checkpoint format")
        _restore_adapter_state(self.model, payload["adapter_state"])
        self.rca_optimizer.load_state_dict(payload["rca_optimizer_state"])
        self.action_optimizer.load_state_dict(payload["action_optimizer_state"])
        self.current_policy_version = str(payload["current_policy_version"])
        self.policy_version_root = str(payload.get("policy_version_root") or self.current_policy_version.split("@u", 1)[0])
        self.bundle_update_step = int(payload["bundle_update_step"])
        self.rca_update_step = int(payload["rca_update_step"])
        self.action_update_step = int(payload["action_update_step"])
        _freeze_everything(self.model)
        return {
            "current_policy_version": self.current_policy_version,
            "policy_version_root": self.policy_version_root,
            "bundle_update_step": self.bundle_update_step,
            "rca_update_step": self.rca_update_step,
            "action_update_step": self.action_update_step,
            "last_update": payload.get("last_update"),
        }
