from __future__ import annotations

"""Production joint trainer for the two prompt-policy LoRA adapters.

The shared base and frozen downstream agents never update. Each frozen rollout
batch is generated by one published adapter bundle, scored by either the live
sparse Twin or the explicit offline debug verifier, then applied atomically to
the RCA and Action adapters using exact-token factorized GRPO.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any


def _append_jsonl(path: Path, row: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(row, sort_keys=True, default=str) + "\n")


def _stamp(
    row: dict[str, Any], *, sync_batch_id: str, adapter_id: str, optimizer_role: str
) -> dict[str, Any]:
    out = dict(row)
    metadata = dict(out.get("metadata", {}) or {})
    metadata.update(
        {
            "sync_batch_id": sync_batch_id,
            "adapter_id": adapter_id,
            "optimizer_role": optimizer_role,
            "update_schedule": "synchronized_two_adapter_atomic_publish",
        }
    )
    out["metadata"] = metadata
    out["sync_batch_id"] = sync_batch_id
    out["adapter_id"] = adapter_id
    return out


def _enable_gradient_checkpointing(model: Any) -> str:
    enable = getattr(model, "gradient_checkpointing_enable", None)
    if not callable(enable):
        return "unsupported"
    try:
        enable(gradient_checkpointing_kwargs={"use_reentrant": False})
        return "nonreentrant"
    except TypeError:
        enable()
        return "model_default"


def _parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description="Train RCA/Action Qwen prompt policies with factorized GRPO")
    ap.add_argument("--processed_states", required=True)
    ap.add_argument("--output_dir", required=True)
    ap.add_argument("--scenario_ids", default=None)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--model", default="Qwen/Qwen3-Coder-30B-A3B-Instruct")
    ap.add_argument(
        "--model_cache_dir", default=None,
        help="Explicit Hugging Face cache directory; overrides inherited cache locations.",
    )
    ap.add_argument(
        "--device", default=None,
        help="Legacy single-device override. Prefer --devices for parallel rollout.",
    )
    ap.add_argument(
        "--devices", default="auto",
        help="Comma-separated CUDA devices, or 'auto' to use every visible GPU.",
    )
    ap.add_argument("--quantization", choices=["nf4", "bf16"], default="nf4")
    ap.add_argument("--experts_implementation", choices=["eager", "batched_mm", "grouped_mm"], default="eager")
    ap.add_argument("--trajectory_group_size", type=int, default=4)
    ap.add_argument(
        "--scenarios_per_update", type=int, default=None,
        help="Frozen-policy scenarios per atomic update; defaults to the worker count.",
    )
    ap.add_argument("--rca_max_iterations", type=int, default=3)
    ap.add_argument("--action_max_iterations", type=int, default=3)
    ap.add_argument("--max_new_tokens", type=int, default=96)
    ap.add_argument("--temperature", type=float, default=0.8)
    ap.add_argument("--top_p", type=float, default=0.95)
    ap.add_argument("--learning_rate", type=float, default=5e-6)
    ap.add_argument("--kl_coeff", type=float, default=0.01)
    ap.add_argument("--lora_r", type=int, default=16)
    ap.add_argument("--lora_alpha", type=int, default=32)
    ap.add_argument("--policy_version", default="qwen-live-grpo-v1")
    ap.add_argument("--resume", default=None)
    ap.add_argument(
        "--reset_data_cursor_on_resume",
        action="store_true",
        help=(
            "Load adapter/optimizer/policy-version state but start the newly "
            "selected dataset at row zero (for offline-to-live curriculum changes)."
        ),
    )
    ap.add_argument("--twin_mode", choices=["live", "offline_debug"], default="live")
    ap.add_argument("--source_namespace", default="test-social-network")
    ap.add_argument("--application_source_root", default="AIOpsLab/aiopslab-applications/socialNetwork")
    ap.add_argument("--state_abstraction_root", default="state_abstraction_full")
    ap.add_argument("--min_twin_reproduction_score", type=float, default=0.1)
    ap.add_argument("--max_serialized_chars", type=int, default=42_000)
    ap.add_argument("--max_system_services", type=int, default=12)
    ap.add_argument("--max_metric_services", type=int, default=64)
    ap.add_argument("--max_log_services", type=int, default=8)
    ap.add_argument("--downstream_rca_tokens", type=int, default=96)
    ap.add_argument("--downstream_action_tokens", type=int, default=192)
    return ap


def _resolve_devices(args: argparse.Namespace, torch: Any) -> list[str]:
    if args.device:
        raw = [str(args.device)]
    elif str(args.devices).strip().lower() == "auto":
        raw = [f"cuda:{index}" for index in range(int(torch.cuda.device_count()))]
    else:
        raw = [part.strip() for part in str(args.devices).split(",") if part.strip()]
    if not raw:
        raise ValueError("no CUDA rollout devices were selected")
    normalized: list[str] = []
    for value in raw:
        device = torch.device(value)
        if device.type != "cuda":
            raise ValueError(f"parallel Qwen rollout requires CUDA devices; got {value!r}")
        index = torch.cuda.current_device() if device.index is None else int(device.index)
        if index < 0 or index >= int(torch.cuda.device_count()):
            raise ValueError(f"CUDA device index is unavailable: {value!r}")
        canonical = f"cuda:{index}"
        if canonical in normalized:
            raise ValueError(f"duplicate rollout device: {canonical}")
        normalized.append(canonical)
    return normalized


@dataclass
class _RolloutWorker:
    index: int
    device: str
    model: Any
    rca_policy: Any
    rca_solver: Any
    action_policy: Any
    action_agent: Any
    twin: Any
    checkpointing: str


def _run_worker_rollout(
    worker: _RolloutWorker,
    rec: Any,
    *,
    batch_offset: int,
    args: argparse.Namespace,
    policy_version: str,
    bounded: Any,
    run_end_to_end_trajectory_group: Any,
) -> dict[str, Any]:
    import torch

    # Some CUDA libraries consult the thread-local current device even when all
    # tensors carry an explicit placement. Keep each rollout thread pinned.
    with torch.cuda.device(worker.device):
        result = run_end_to_end_trajectory_group(
            rec.full_state, rec.compressed_state,
            rca_instruction_policy=worker.rca_policy, rca_solver=worker.rca_solver,
            action_prompt_policy=worker.action_policy, action_agent=worker.action_agent,
            twin_verifier=worker.twin, trajectory_group_size=args.trajectory_group_size,
            rca_max_iterations=args.rca_max_iterations,
            action_max_iterations=args.action_max_iterations,
            rca_policy_model_name=f"{args.model}+lora_rca",
            action_policy_model_name=f"{args.model}+lora_action",
            policy_version=policy_version,
            min_twin_reproduction_score=args.min_twin_reproduction_score,
            bounded_agent_state_config=bounded,
        )
    return {
        "worker_index": worker.index,
        "worker_device": worker.device,
        "batch_offset": batch_offset,
        "scenario_id": rec.scenario_id,
        "result": result,
    }


def main() -> None:
    args = _parser().parse_args()
    if args.trajectory_group_size < 2:
        raise ValueError("--trajectory_group_size must be >= 2")
    if args.scenarios_per_update is not None and args.scenarios_per_update < 1:
        raise ValueError("--scenarios_per_update must be >= 1")

    # Heavy imports stay inside main so --help/config audits work without CUDA.
    import torch
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is unavailable; production Qwen GRPO requires a CUDA worker")
    devices = _resolve_devices(args, torch)
    scenarios_per_update = (
        len(devices) if args.scenarios_per_update is None else int(args.scenarios_per_update)
    )
    if scenarios_per_update > len(devices):
        raise ValueError(
            "--scenarios_per_update cannot exceed the number of rollout devices; "
            "each model replica may execute only one scenario at a time"
        )

    from digital_twin_runtime.sparse_live_verifier import SparseLiveTwinVerifier, SparseLiveVerifierConfig
    from digital_twin_runtime.twin_verifier import BehavioralTwinVerifier
    from digital_twin_runtime.live_capabilities import audit_live_training_records
    from .bounded_agent_state import BoundedAgentStateConfig
    from .data_loader import iter_scenarios
    from .end_to_end_loop import run_end_to_end_trajectory_group
    from .factorized_grpo_learner import FactorizedGRPOConfig
    from .frozen_qwen_agents import (
        FrozenBaseGenerationConfig, FrozenBaseQwenGenerator,
        FrozenQwenActionAgent, FrozenQwenRCASolver,
    )
    from .ground_truth import labels_from_full_state
    from .hf_exact_token_sampler import ExactTokenGenerationConfig, HFExactTokenPolicySampler
    from .peft_adapter_control import copy_role_adapter_parameters
    from .qwen_shared_policy_backend import QwenSharedPolicyBackendConfig, load_qwen_shared_policy_backend
    from .split_utils import read_scenario_ids
    from .streaming_synchronized_grpo_trainer import StreamingSynchronizedFactorizedGRPOTrainer
    from .synchronized_grpo_trainer import SynchronizedGRPOTrainerConfig
    from .trainable_hf_prompt_policies import TrainableHFActionPromptPolicy, TrainableHFRCAInstructionPolicy

    allowed = read_scenario_ids(args.scenario_ids)
    records = [r for r in iter_scenarios(args.processed_states, allowed_ids=allowed)
               if labels_from_full_state(r.full_state)]
    if args.limit is not None:
        records = records[:args.limit]
    if not records:
        raise RuntimeError("no labeled scenarios matched the requested training selection")
    if args.twin_mode == "live":
        live_preflight = audit_live_training_records(records)
        if not live_preflight["all_supported"]:
            preview = live_preflight["unsupported"][:10]
            raise ValueError(
                "live training selection contains unaudited mechanism/workload pairs; "
                f"use configs/live_supported_scenarios.txt: {preview}"
            )

    out_dir = Path(args.output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    checkpoint = out_dir / "latest.pt"
    event_path = out_dir / "training_events.jsonl"
    trajectory_path = out_dir / "joint_trajectories.jsonl"

    workers: list[_RolloutWorker] = []
    backends: list[Any] = []
    for worker_index, device in enumerate(devices):
        with torch.cuda.device(device):
            backend = load_qwen_shared_policy_backend(QwenSharedPolicyBackendConfig(
                model_name=args.model, cache_dir=args.model_cache_dir,
                device=device, quantization=args.quantization,
                experts_implementation=args.experts_implementation, lora_r=args.lora_r,
                lora_alpha=args.lora_alpha, lora_dropout=0.0,
            ))
        backends.append(backend)
        model, tokenizer = backend.model, backend.tokenizer
        if hasattr(model.config, "use_cache"):
            model.config.use_cache = False
        checkpointing = _enable_gradient_checkpointing(model)
        sampler = HFExactTokenPolicySampler(model, tokenizer, config=ExactTokenGenerationConfig(
            max_new_tokens=args.max_new_tokens, temperature=args.temperature,
            top_p=args.top_p, do_sample=True, max_prompt_tokens=None,
            seed=240828 + worker_index,
            prompt_format="chat_template", chat_role="user",
        ), device=device)
        rca_policy = TrainableHFRCAInstructionPolicy(
            sampler, adapter_name="lora_rca", max_iterations=args.rca_max_iterations
        )
        action_policy = TrainableHFActionPromptPolicy(sampler, adapter_name="lora_action")
        frozen_generator = FrozenBaseQwenGenerator(
            model, tokenizer,
            config=FrozenBaseGenerationConfig(
                rca_max_new_tokens=args.downstream_rca_tokens,
                action_max_new_tokens=args.downstream_action_tokens,
            ),
            device=device,
        )
        if args.twin_mode == "live":
            twin = SparseLiveTwinVerifier(SparseLiveVerifierConfig(
                source_namespace=args.source_namespace,
                application_source_root=str(Path(args.application_source_root).resolve()),
                state_abstraction_root=str(Path(args.state_abstraction_root).resolve()),
                reproduction_threshold=args.min_twin_reproduction_score,
            ))
        else:
            twin = BehavioralTwinVerifier()
        workers.append(_RolloutWorker(
            index=worker_index,
            device=device,
            model=model,
            rca_policy=rca_policy,
            rca_solver=FrozenQwenRCASolver(frozen_generator),
            action_policy=action_policy,
            action_agent=FrozenQwenActionAgent(frozen_generator),
            twin=twin,
            checkpointing=checkpointing,
        ))

    learner = workers[0]
    model = learner.model

    trainer = StreamingSynchronizedFactorizedGRPOTrainer(
        model, current_policy_version=args.policy_version,
        config=SynchronizedGRPOTrainerConfig(
            rca_learning_rate=args.learning_rate,
            action_learning_rate=args.learning_rate,
            grpo=FactorizedGRPOConfig(kl_coeff=args.kl_coeff),
        ), device=learner.device,
    )
    completed = 0
    resume_path = Path(args.resume).expanduser() if args.resume else None
    if resume_path:
        restored = trainer.load_checkpoint(resume_path)
        completed = (
            0
            if args.reset_data_cursor_on_resume
            else int((restored.get("last_update") or {}).get("scenarios_completed", 0))
        )
    for replica in workers[1:]:
        copy_role_adapter_parameters(learner.model, replica.model)

    bounded = BoundedAgentStateConfig(
        max_serialized_chars=args.max_serialized_chars,
        max_system_services=args.max_system_services,
        max_metric_services=args.max_metric_services,
        max_log_services=args.max_log_services,
    )
    if completed > len(records):
        raise ValueError("checkpoint scenario cursor exceeds the selected dataset")

    updates = trainer.bundle_update_step
    while completed < len(records):
        sync_id = f"live-update-{updates:06d}"
        batch_count = min(scenarios_per_update, len(records) - completed)
        batch_records = records[completed:completed + batch_count]
        rollout_policy_version = trainer.current_policy_version
        worker_results: list[dict[str, Any]] = []
        with ThreadPoolExecutor(max_workers=min(len(workers), batch_count)) as pool:
            futures = {
                pool.submit(
                    _run_worker_rollout,
                    workers[offset % len(workers)],
                    rec,
                    batch_offset=offset,
                    args=args,
                    policy_version=rollout_policy_version,
                    bounded=bounded,
                    run_end_to_end_trajectory_group=run_end_to_end_trajectory_group,
                ): offset
                for offset, rec in enumerate(batch_records)
            }
            for future in as_completed(futures):
                worker_results.append(future.result())
        worker_results.sort(key=lambda row: int(row["batch_offset"]))

        batch_rca: list[dict[str, Any]] = []
        batch_action: list[dict[str, Any]] = []
        for worker_result in worker_results:
            result = worker_result["result"]
            _append_jsonl(trajectory_path, {
                "scenario_id": worker_result["scenario_id"],
                "sync_batch_id": sync_id,
                "policy_version": rollout_policy_version,
                "worker_index": worker_result["worker_index"],
                "worker_device": worker_result["worker_device"],
                "trajectories": result.get("trajectories"),
            })
            batch_rca.extend(
                _stamp(x, sync_batch_id=sync_id, adapter_id="lora_rca", optimizer_role="rca_policy")
                for x in result.get("rca_grpo_samples", [])
            )
            batch_action.extend(
                _stamp(x, sync_batch_id=sync_id, adapter_id="lora_action", optimizer_role="action_policy")
                for x in result.get("action_grpo_samples", [])
            )
        completed += batch_count
        if not batch_rca or not batch_action:
            raise RuntimeError("joint batch lacks RCA or Action optimizer rows; inspect live gate failures")
        update = trainer.update_joint_batch(batch_rca, batch_action)
        updates = trainer.bundle_update_step
        copied_adapter_tensors = 0
        for replica in workers[1:]:
            copied_adapter_tensors += copy_role_adapter_parameters(learner.model, replica.model)
        update["scenarios_completed"] = completed
        update["twin_mode"] = args.twin_mode
        update["gradient_checkpointing"] = {
            worker.device: worker.checkpointing for worker in workers
        }
        update["rollout_devices"] = devices
        update["parallel_rollout_workers"] = len(workers)
        update["scenarios_in_update"] = batch_count
        update["replica_adapter_tensors_copied"] = copied_adapter_tensors
        trainer.save_checkpoint(checkpoint, last_update=update)
        _append_jsonl(event_path, update)
        print(json.dumps(update, sort_keys=True, default=str))

    summary = {
        "status": "COMPLETE", "scenarios_completed": completed,
        "bundle_updates": trainer.bundle_update_step,
        "policy_version": trainer.current_policy_version,
        "checkpoint": str(checkpoint), "twin_mode": args.twin_mode,
        "reward_mode": "factorized_joint_pipeline_v2_no_double_count",
        "frozen_downstream_agents": True, "exact_token_rollouts": True,
        "atomic_two_adapter_updates": True,
        "rollout_devices": devices,
        "parallel_rollout_workers": len(workers),
        "scenarios_per_update": scenarios_per_update,
        "parallelism_mode": "synchronous_same-policy_multi-gpu_rollout_single-learner",
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True))
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
